steps:
  # Step 1: Construir la imagen Docker si los tests pasan
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/calculadorajs/calcjs:js'
      - '--build-arg=RUN_TESTS=true'  # Pasar el argumento para ejecutar los tests
      - '.'

  # Step 2: Push la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/calculadorajs/calcjs:js'
  # Step 3: Tag la imagen para Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'us-docker.pkg.dev/still-descent-423419-c7/calculadorajs/calcjs:js'
      - 'valentingarciairiart/calcjs:js'

  # Step 4: Login en Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'login'
      - '-u'
      - '${_DOCKER_USERNAME}'
      - '-p'
      - '${_DOCKER_PASSWORD}'

  # Step 5: Push la imagen a Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'valentingarciairiart/calcjs:js'

# Lista de imágenes para que Cloud Build las reconozca
images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/calculadorajs/calcjs:js'
  - 'valentingarciairiart/calcjs:js'

# Definir condiciones de éxito para detener la construcción si los tests fallan
options:
  success:
    if: "steps['Run tests'].status == 'SUCCESS'"