steps:
  # Step 1: Instalar dependencias
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['install']
  
  # Step 2: Ejecutar los tests
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['test']

  # Step 3: Construir la imagen Docker si los tests pasan
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/calculadorajs/calculadoraJS:js'
      - '.'

  # Step 4: Push la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/calculadorajs/calculadoraJS:js'

  # Step 5: Tag la imagen para Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'us-docker.pkg.dev/still-descent-423419-c7/calculadorajs/calculadoraJS:js'
      - 'valentingarciairiart/calculadoraJS:js'

  # Step 6: Login en Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'login'
      - '-u'
      - '${_DOCKER_USERNAME}'
      - '-p'
      - '${_DOCKER_PASSWORD}'

  # Step 7: Push la imagen a Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'valentingarciairiart/calculadoraJS:js'

# Lista de imágenes para que Cloud Build las reconozca
images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/calculadorajs/calculadoraJS:js'
  - 'valentingarciairiart/calculadoraJS:js'
